# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\detail_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import os
import pathlib
import sys

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QAbstractItemView, QDialog

import edit_cell_dialog
import file_helper
from pandas_model import PandasModel


class Ui_Dialog(object):

    def __init__(self, filename):
        self.filename = filename

    def setupUi(self, Dialog):
        Dialog.setObjectName("File details")
        Dialog.resize(629, 514)
        self.tableView = QtWidgets.QTableView(Dialog)
        self.tableView.setGeometry(QtCore.QRect(10, 40, 611, 431))
        self.tableView.setObjectName("tableView")
        self.tableView.setSelectionMode(QAbstractItemView.SelectionMode.SingleSelection)
        self.tableView.doubleClicked.connect(self.update_value)
        self.btnUpdateValue = QtWidgets.QPushButton(Dialog, clicked=lambda: self.update_value())
        self.btnUpdateValue.setGeometry(QtCore.QRect(10, 10, 101, 23))
        self.btnUpdateValue.setObjectName("btnUpdateValue")
        self.btnDeleteValue = QtWidgets.QPushButton(Dialog, clicked=lambda: self.delete_value())
        self.btnDeleteValue.setGeometry(QtCore.QRect(120, 10, 75, 23))
        self.btnDeleteValue.setObjectName("btnDeleteValue")
        self.btnDeleteRow = QtWidgets.QPushButton(Dialog, clicked=lambda: self.delete_row())
        self.btnDeleteRow.setGeometry(QtCore.QRect(200, 10, 75, 23))
        self.btnDeleteRow.setObjectName("btnDeleteRow")
        self.btnDeleteColumn = QtWidgets.QPushButton(Dialog, clicked=lambda: self.delete_column())
        self.btnDeleteColumn.setGeometry(QtCore.QRect(280, 10, 75, 23))
        self.btnDeleteColumn.setObjectName("btnDeleteColumn")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        self.update_data()

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.btnUpdateValue.setText(_translate("Dialog", "Update value"))
        self.btnDeleteValue.setText(_translate("Dialog", "Clear value"))
        self.btnDeleteRow.setText(_translate("Dialog", "Delete row"))
        self.btnDeleteColumn.setText(_translate("Dialog", "Delete column"))

    def update_data(self):
        full_filename = os.path.join(file_helper.output_directory, self.filename)
        filepath = pathlib.Path(full_filename)
        file_type = filepath.suffix
        df = file_helper.parse_file(full_filename, file_type)

        model = PandasModel(df)
        self.tableView.setModel(model)

    def delete_value(self):
        indexes = self.tableView.selectionModel().selectedIndexes()

        if len(indexes) > 0:
            index = indexes[0]
            file_helper.update_cell_value(self.filename, index.row(), index.column(), None)
            self.update_data()

    def delete_row(self):
        indexes = self.tableView.selectionModel().selectedIndexes()

        if len(indexes) > 0:
            index = indexes[0]
            file_helper.delete_col_or_row(self.filename, index.row(), is_row=True)
            self.update_data()

    def delete_column(self):
        indexes = self.tableView.selectionModel().selectedIndexes()

        if len(indexes) > 0:
            index = indexes[0]
            file_helper.delete_col_or_row(self.filename, index.column(), is_row=False)
            self.update_data()

    def update_value(self):
        indexes = self.tableView.selectionModel().selectedIndexes()

        if len(indexes) > 0:
            index = indexes[0]
            value = self.tableView.model().index(index.row(), index.column()).data()
            dialog = QDialog()
            edit_cell_dialog_object = edit_cell_dialog.Ui_Dialog(value)
            dialog.ui = edit_cell_dialog_object
            dialog.ui.setupUi(dialog)

            if dialog.exec_():
                file_helper.update_cell_value(self.filename, index.row(), index.column(), edit_cell_dialog_object.updated_text())
                self.update_data()
