= Exercise 4
:author: Andreas Wenzelhuemer
:email: <S1910307106@fhooe.at>
:reproducible:
:experimental:
:listing-caption: Listing
:source-highlighter: rouge
:img: ./img
:src: ../src
:toc:
:numbered:
:toclevels: 5
:rouge-style: github

<<<
== Garbage collection

Python besitzt eine automatische Speicherfreigabe.
Nicht mehr referenzierte Objekte werden vom Speicher freigegeben.
Jedes Objekt besitzt einen Typ, Wert und einen Referenz-Zähler.
Beim Referenz-Zähler wird dabei angegeben, wie oft das Objekt von Namen referenziert wird.

[source,python]
----
a = 1 # refs: 1
b = a # refs: 2

a = None # refs: 1
b = None # refs: 0
----
Wenn der Referenz-Zähler 0 erreicht, würde das Objekt gelöscht werden.
In diesem Fall wäre dies, nachdem b auf None gesetzt wurde.
Diese Variante mit dem Mitzählen von Referenzen funktioniert zwar ganz gut, es kann aber zu zyklischen Referenzen kommen.
Wenn das Objekt eine Referenz auf sich selbst bezieht, würde diese Variante nicht funktionieren.
Ein einfaches Beispiel wäre eine Referenz auf sich selbst, indem eine Liste in sich selbst eingefügt wird.

[source, python]
----
a = []
a.append(a)
print(a)
----
Das Objekt wird dabei nie gelöscht, da der Referenz-Zähler nie 0 erreicht. Für dieses Problem gibt es eine zweite Art der Garbage Collection, die sogenannte Generational Garbage Collection.

Dabei werden bei einem Programmlauf drei Listen erstellt: Generation 0, 1 and 2.
Neu erstellte Objekte werden in die Generation 0 Liste eingefügt.
Zyklische Abhängigkeiten werden erkannt, wenn ein Objekt keine Referenzen von außerhalb besitzt wird es entfernt.
Objekte, welche überbleiben, landen in der Generation 1 Liste.
Die gleichen Schritte wie auch bei der Generation 0 Liste werden ausgeführt. Überlebende Objekte dieser Liste landen danach in der Generation 2 Liste. Diese Objekte bleiben für den ganzen Programmlauf bestehen.

<<<
== Sys & Garbage Collector Module

Mit sys.getrefcount kann die Anzahl der Referenzen zurückgegeben werden. Der kleinstmögliche Wert beträgt dabei drei, da zwei Referenzen von der Funktion erstellt werden und einer durch die Objekterstellung vorhanden ist.

[source, python]
----
import sys

print(sys.getrefcount(1000)) # refs: 3
a = 1000
print(sys.getrefcount(a)) # refs: 4
a = None
print(sys.getrefcount(1000)) # refs: 3
----

Mit dem gc-Modul kann das Verhalten des Garbage-Collectors verändert werden.

[source, python]
----
import gc

gc.set_threshold(10, 10, 1)
gc.set_threshold(0, 0, 0)
collected_count = gc.collect()
collected_count = gc.collect(0)
collected_count = gc.collect(1)
collected_count = gc.collect(2)
----

Mittels set_treshold kann festgelegt werden, ab wann die Garbage-Collection für die einzelnen Listen erfolgen soll.
Wenn set_treshold auf 0 gesetzt wird, wird die Garbage-Collection deaktiviert.
Mit gc.collect() kann diese manuell für alle oder für einzelne Listen angestoßen werden.

<<<
== Memory Profiling Monte Carlo Walk Analysis

Die Variante mit dem deaktivierten gen_walk Flag weißt dabei einen wesentlich geringeren Memory Peak auf als die originale Variante ohne Flag

1. Zeile 87: Hier werden nur Distanzen zurückgegeben, anstelle der Walks None.
2. Zeile 132: Das Dictionary enthält lediglich ein Tuple mit Distanzen und benötigt daher um einiges weniger Speicher
3. Zeile 81: Die Walks aus der Generator-Function müssen bei deaktiviertem Flag nicht in eine Liste umgewandelt werden.

----
Memory peak (monte_carlo_walk_analysis): 46826264
Memory peak (monte_carlo_walk): 12914112
Allocations:
c:\Users\Andi\Documents\GitHub\fh-se-python\exercise\Ue04\src\Memory.py:89: size=110 KiB (+110 KiB), count=1996 (+1996), average=56 B
c:\Users\Andi\Documents\GitHub\fh-se-python\exercise\Ue04\src\Memory.py:87: size=0 B (-110 KiB), count=0 (-1996)
c:\Users\Andi\Documents\GitHub\fh-se-python\exercise\Ue04\src\Memory.py:132: size=1728 B (+1728 B), count=22 (+22), average=79 B
c:\Users\Andi\Documents\GitHub\fh-se-python\exercise\Ue04\src\Memory.py:81: size=3192 B (-1176 B), count=57 (-21), average=56 B
C:\Users\Andi\AppData\Local\Programs\Python\Python310\lib\tracemalloc.py:558: size=952 B (+896 B), count=17 (+16), average=56 B
C:\Users\Andi\AppData\Local\Programs\Python\Python310\lib\tracemalloc.py:423: size=568 B (+568 B), count=4 (+4), average=142 B
C:\Users\Andi\AppData\Local\Programs\Python\Python310\lib\tracemalloc.py:560: size=464 B (+464 B), count=2 (+2), average=232 B
c:\Users\Andi\Documents\GitHub\fh-se-python\exercise\Ue04\src\Memory.py:144: size=440 B (+440 B), count=1 (+1), average=440 B
c:\Users\Andi\Documents\GitHub\fh-se-python\exercise\Ue04\src\Memory.py:147: size=416 B (+416 B), count=1 (+1), average=416 B
c:\Users\Andi\Documents\GitHub\fh-se-python\exercise\Ue04\src\Memory.py:141: size=0 B (-416 B), count=0 (-1)
c:\Users\Andi\Documents\GitHub\fh-se-python\exercise\Ue04\src\Memory.py:66: size=710 B (+168 B), count=7 (+3), average=101 B
c:\Users\Andi\Documents\GitHub\fh-se-python\exercise\Ue04\src\Memory.py:145: size=112 B (+112 B), count=3 (+3), average=37 B
c:\Users\Andi\Documents\GitHub\fh-se-python\exercise\Ue04\src\Memory.py:51: size=56 B (+56 B), count=1 (+1), average=56 B
C:\Users\Andi\AppData\Local\Programs\Python\Python310\lib\tracemalloc.py:313: size=48 B (+48 B), count=1 (+1), average=48 B
C:\Users\Andi\AppData\Local\Programs\Python\Python310\lib\tracemalloc.py:315: size=40 B (+40 B), count=1 (+1), average=40 B
c:\Users\Andi\Documents\GitHub\fh-se-python\exercise\Ue04\src\Memory.py:83: size=432 B (+0 B), count=1 (+0), average=432 B
C:\Users\Andi\AppData\Local\Programs\Python\Python310\lib\random.py:378: size=432 B (+0 B), count=1 (+0), average=432 B
c:\Users\Andi\Documents\GitHub\fh-se-python\exercise\Ue04\src\Memory.py:25: size=152 B (+0 B), count=2 (+0), average=76 B
c:\Users\Andi\Documents\GitHub\fh-se-python\exercise\Ue04\src\Memory.py:68: size=144 B (+0 B), count=2 (+0), average=72 B
c:\Users\Andi\Documents\GitHub\fh-se-python\exercise\Ue04\src\Memory.py:27: size=84 B (+0 B), count=2 (+0), average=42 B
c:\Users\Andi\Documents\GitHub\fh-se-python\exercise\Ue04\src\Memory.py:53: size=76 B (+0 B), count=2 (+0), average=38 B
C:\Users\Andi\AppData\Local\Programs\Python\Python310\lib\random.py:239: size=61 B (+0 B), count=2 (+0), average=30 B
C:\Users\Andi\AppData\Local\Programs\Python\Python310\lib\random.py:375: size=41 B (+0 B), count=2 (+0), average=20 B
----
.Ausgabe

<<<
=== Quellcode
[source, python]
----
include::{src}/Memory.py[]
----